export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      inherit: 'inherit',

      luna: {
        50: 'var(--luna-50)',
        100: 'var(--luna-100)',
        200: 'var(--luna-200)',
        300: 'var(--luna-300)',
        400: 'var(--luna-400)',
        500: 'var(--luna-500)',
        600: 'var(--luna-600)',
        700: 'var(--luna-700)',
        800: 'var(--luna-800)',
        900: 'var(--luna-900)',
      },

      xp: {
        frame: 'var(--xp-frame)',
        'taskbar-btn': 'var(--xp-taskbar-btn)',
        'taskbar-btn-active': 'var(--xp-taskbar-btn-active)',
        tray: 'var(--xp-tray)',
        select: 'var(--xp-select)',
        close: 'var(--xp-close)',
        'close-hover': 'var(--xp-close-hover)',
        'close-pressed': 'var(--xp-close-pressed)',
        ctl: 'var(--xp-ctl)',
        'btn-border': 'var(--xp-btn-border)',
        'hover-glow': 'var(--xp-hover-glow)',
        'hover-glow-hi': 'var(--xp-hover-glow-hi)',
        'title-emboss': 'var(--xp-title-emboss)',
      },

      paper: {
        50: 'var(--paper-50)',
        100: 'var(--paper-100)',
        edge: 'var(--paper-edge)',
        300: 'var(--paper-300)',
        tape: 'var(--paper-tape)',
        900: 'var(--paper-900)',
      },
      note: 'var(--note)',
      'note-edge': 'var(--note-edge)',
      tooltip: 'var(--tooltip)',
      'develop-veil': 'var(--develop-veil)',

      green: {
        500: 'var(--green-500)',
        600: 'var(--green-600)',
        700: 'var(--green-700)',
        boot: 'var(--green-boot)',
      },

      n: {
        0: 'var(--n-0)',
        50: 'var(--n-50)',
        100: 'var(--n-100)',
        150: 'var(--n-150)',
        200: 'var(--n-200)',
        300: 'var(--n-300)',
        400: 'var(--n-400)',
        500: 'var(--n-500)',
        600: 'var(--n-600)',
        800: 'var(--n-800)',
        900: 'var(--n-900)',
      },
      field: 'var(--field)',
      'field-disabled': 'var(--field-disabled)',
      'btn-disabled': 'var(--btn-disabled)',

      ink: 'var(--ink)',
      'ink-2': 'var(--ink-2)',
      'ink-disabled': 'var(--ink-disabled)',
      'ink-on-color': 'var(--ink-on-color)',
      link: 'var(--link)',
      'link-hover': 'var(--link-hover)',
      pen: 'var(--pen)',
      'field-border': 'var(--field-border)',
      'field-border-hover': 'var(--field-border-hover)',
      'field-border-focus': 'var(--field-border-focus)',
      'caption-halo': 'var(--caption-halo)',
      'caption-halo-soft': 'var(--caption-halo-soft)',

      success: 'var(--success)',
      danger: 'var(--danger)',
      info: 'var(--info)',
      concept: {
        fill: 'var(--concept-fill)',
        border: 'var(--concept-border)',
        ink: 'var(--concept-ink)',
      },

      surface: {
        window: 'var(--surface-window)',
        paper: 'var(--surface-paper)',
        sunken: 'var(--surface-sunken)',
        field: 'var(--surface-field)',
        overlay: 'var(--surface-overlay)',
      },

      boot: {
        bg: 'var(--boot-bg)',
        ink: 'var(--boot-ink)',
        dim: 'var(--boot-dim)',
        ok: 'var(--boot-ok)',
      },

      focus: {
        gap: 'var(--focus-gap)',
        ring: 'var(--focus-ring)',
      },
    },

    fontFamily: {
      ui: 'var(--font-ui)',
      display: 'var(--font-display)',
      hand: 'var(--font-hand)',
      mono: 'var(--font-mono)',
    },

    fontSize: {
      'display-xl': ['var(--fs-display-xl)', { lineHeight: 'var(--lh-display-xl)', letterSpacing: 'var(--ls-display-xl)' }],
      'display-l': ['var(--fs-display-l)', { lineHeight: 'var(--lh-display-l)', letterSpacing: 'var(--ls-display-l)' }],
      'display-m': ['var(--fs-display-m)', { lineHeight: 'var(--lh-display-m)', letterSpacing: 'var(--ls-display-m)' }],
      title: ['var(--fs-title)', { lineHeight: 'var(--lh-title)', letterSpacing: 'var(--ls-title)' }],
      lead: ['var(--fs-lead)', { lineHeight: 'var(--lh-lead)' }],
      body: ['var(--fs-body)', { lineHeight: 'var(--lh-body)' }],
      ui: ['var(--fs-ui)', { letterSpacing: 'var(--ls-ui)' }],
      small: ['var(--fs-small)', { lineHeight: 'var(--lh-small)' }],
      chrome: ['var(--fs-chrome)', { lineHeight: 'var(--lh-chrome)' }],
      meta: ['var(--fs-meta)', { lineHeight: 'var(--lh-meta)', letterSpacing: 'var(--ls-meta)' }],
      'hand-note': ['var(--fs-hand-note)', { lineHeight: 'var(--lh-hand-note)' }],
      'hand-caption': ['var(--fs-hand-caption)', { lineHeight: 'var(--lh-hand-caption)', letterSpacing: 'var(--ls-hand-caption)' }],
      'hand-head': ['var(--fs-hand-head)', { lineHeight: 'var(--lh-hand-head)' }],
      boot: ['var(--fs-boot)', { lineHeight: 'var(--lh-boot)' }],
      field: ['var(--fs-field)'],
    },

    boxShadow: {
      xs: 'var(--shadow-xs)',
      paper: 'var(--shadow-paper)',
      object: 'var(--shadow-object)',
      'object-lift': 'var(--shadow-object-lift)',
      note: 'var(--shadow-note)',
      window: 'var(--shadow-window)',
      'window-inactive': 'var(--shadow-window-inactive)',
      menu: 'var(--shadow-menu)',
      'field-inset': 'var(--shadow-field-inset)',
      'btn-highlight': 'var(--shadow-btn-highlight)',
      press: 'var(--shadow-press)',
      'press-neutral': 'var(--shadow-press-neutral)',
      'hover-glow': 'var(--shadow-hover-glow)',
      'bevel-raised': 'var(--bevel-raised)',
      'bevel-sunken': 'var(--bevel-sunken)',
      focus: 'var(--focus-shadow)',
    },

    borderRadius: {
      none: 'var(--radius-0)',
      paper: 'var(--radius-paper)',
      control: 'var(--radius-control)',
      tile: 'var(--radius-tile)',
      window: 'var(--radius-window)',
      start: 'var(--radius-start)',
      full: 'var(--radius-round)',
    },

    transitionTimingFunction: {
      out: 'var(--ease-out)',
      lift: 'var(--ease-lift)',
      in: 'var(--ease-in)',
      draw: 'var(--ease-draw)',
      press: 'var(--ease-press)',
      linear: 'var(--ease-linear)',
    },

    extend: {},
  },
  plugins: [],
}
